name: Build-Release

on:
  workflow_dispatch: {}
  push:
    paths:
      - 'src/**'

jobs:
  build:
    name: Build binary
    runs-on: windows-2022
    strategy:
      matrix:
        configuration:
          - Release

    steps:
      - name: Wait for previous workflows
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out files
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
          lfs: false

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Generate project files
        run: tools/premake5 vs2022

      - name: Set up problem matching
        uses: ammaraskar/msvc-problem-matcher@master

      - name: Build ${{matrix.configuration}}-binaries-t4-rtx
        run: msbuild /m /v:minimal /p:Configuration=${{matrix.configuration}} /p:Platform=Win32 build/t4-rtx.sln

      - name: Move build files 
        run: |
          move build/bin/${{matrix.configuration}}/nvapi.dll ./
          move build/bin/${{matrix.configuration}}/t4-rtx.pdb ./

      - name: Upload ${{matrix.configuration}}-binaries-t4-rtx
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.configuration}}-binaries-t4-rtx
          path: |
            ./nvapi.dll
            ./t4-rtx.pdb
            ./assets/
  
  webbook:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Tag String
        id: tag
        run: |
            echo "GIT_TAG=`echo $(git describe --tags --dirty --always)`" >> $GITHUB_ENV
          
            git describe --tags --dirty --always
            # …
        
      - uses: tsickert/discord-webhook@v4.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          username: "GitHub Workflow"
          avatar-url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
          embed-author-icon-url: "https://cdn2.steamgriddb.com/file/sgdb-cdn/icon_thumb/54ed85e7af8edc78637654cb4a89040e.png"
          embed-author-name: "t4-rtx"
          embed-author-url: "https://github.com/xoxor4d/t4-rtx"
          embed-title: "T4-RTX - Successful build (release)"
          embed-color: 0xc680ff
          embed-description: "${{ env.GIT_TAG }} [nightly link](https://nightly.link/xoxor4d/t4-rtx/workflows/build-release/master/Release-binaries-t4-rtx.zip)"